FileVersion = 1

[Project]
Name = "inih-beef"
DefaultNamespace = "inih"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\inihd.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\inih.lib"]